import { Router } from 'express';
import { deleteAdminUser, getAdminEntitlementHistory, getAdminOverview, listAdminUsers, updateAdminEntitlement } from '../controllers/admin.controller.js';
import { getAdminBillingEvents, getAdminBillingSettings, getAdminBillingSettingsAudit, getAdminSubscriptionOperations, patchAdminBillingSettings } from '../controllers/billing-settings.controller.js';
import { getSystemHealth } from '../controllers/system-health.controller.js';
import { getSystemLimitAudit, getSystemLimits, getYoutubeQuotaUsage, patchSystemLimit } from '../controllers/system-limit.controller.js';
import { requireAdmin, requireAuth } from '../middleware/auth.middleware.js';

export const adminRouter = Router();
adminRouter.use(requireAuth, requireAdmin);
adminRouter.get('/overview', getAdminOverview);
adminRouter.get('/system-health', getSystemHealth);
adminRouter.get('/system-limits', getSystemLimits);
adminRouter.get('/system-limits/audit', getSystemLimitAudit);
adminRouter.get('/youtube-quota', getYoutubeQuotaUsage);
adminRouter.patch('/system-limits/:key', patchSystemLimit);
adminRouter.get('/users', listAdminUsers);
adminRouter.patch('/users/:id/entitlement', updateAdminEntitlement);
adminRouter.get('/users/:id/entitlement-history', getAdminEntitlementHistory);
adminRouter.delete('/users/:id', deleteAdminUser);
adminRouter.get('/billing-settings', getAdminBillingSettings);
adminRouter.patch('/billing-settings', patchAdminBillingSettings);
adminRouter.get('/billing-settings/audit', getAdminBillingSettingsAudit);
adminRouter.get('/subscription-operations', getAdminSubscriptionOperations);
adminRouter.get('/billing-events', getAdminBillingEvents);
