import { Router } from 'express';
import { requireAuth } from '../middleware/auth.middleware.js';
import { getHierarchy,createPhase,createModule,createLesson,patchLesson,deletePhase,deleteModule,deleteLesson } from '../controllers/hierarchy.controller.js';
export const hierarchyRouter=Router();
hierarchyRouter.use(requireAuth);
hierarchyRouter.get('/learning-paths/:learningPathId/hierarchy',getHierarchy);
hierarchyRouter.post('/learning-paths/:learningPathId/phases',createPhase);
hierarchyRouter.post('/phases/:phaseId/modules',createModule);
hierarchyRouter.post('/modules/:moduleId/lessons',createLesson);
hierarchyRouter.patch('/lessons/:lessonId',patchLesson);
hierarchyRouter.delete('/phases/:phaseId',deletePhase);
hierarchyRouter.delete('/modules/:moduleId',deleteModule);
hierarchyRouter.delete('/lessons/:lessonId',deleteLesson);
