import type { Response, NextFunction } from 'express';
import { z } from 'zod';
import type { AuthenticatedRequest } from '../middleware/auth.middleware.js';
import { env } from '../config/env.js';
import { LearningPathModel } from '../models/learning-path.model.js';
import { PhaseModel } from '../models/phase.model.js';
import { ModuleModel } from '../models/module.model.js';
import { LessonModel } from '../models/lesson.model.js';
import { UserModel } from '../models/user.model.js';
import { localDateTimeToUtc } from '../utils/timezone.js';

const requestSchema=z.object({topic:z.string().min(2).max(120),weeks:z.number().int().min(1).max(52),days:z.array(z.string()).min(1).max(7),time:z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/),durationMinutes:z.number().int().min(15).max(240).default(60),startDate:z.string().regex(/^\d{4}-\d{2}-\d{2}$/),save:z.boolean().default(false)});
const planSchema=z.object({learningPath:z.object({title:z.string().min(2),description:z.string().optional()}),phases:z.array(z.object({title:z.string().min(1),modules:z.array(z.object({title:z.string().min(1),lessons:z.array(z.object({title:z.string().min(1),description:z.string().optional(),date:z.string(),time:z.string(),durationMinutes:z.number().int().min(5).max(480),resourceUrl:z.string().optional()}))}))}))});
function extractText(data:unknown):string{const value=data as {output_text?:string;output?:Array<{content?:Array<{text?:string}>}>};if(typeof value.output_text==='string')return value.output_text;for(const item of value.output??[])for(const c of item.content??[])if(typeof c.text==='string')return c.text;return '';}
async function persistPlan(ownerId:string,timezone:string,rawPlan:unknown){const plan=planSchema.parse(rawPlan);const path=await LearningPathModel.create({ownerId,title:plan.learningPath.title,description:plan.learningPath.description,status:'ACTIVE'});for(let p=0;p<plan.phases.length;p++){const phaseData=plan.phases[p]!;const phase=await PhaseModel.create({ownerId,learningPathId:path._id,title:phaseData.title,position:p});for(let m=0;m<phaseData.modules.length;m++){const moduleData=phaseData.modules[m]!;const module=await ModuleModel.create({ownerId,learningPathId:path._id,phaseId:phase._id,title:moduleData.title,position:m});for(let l=0;l<moduleData.lessons.length;l++){const lesson=moduleData.lessons[l]!;const scheduledAt=localDateTimeToUtc(lesson.date,lesson.time,timezone);await LessonModel.create({ownerId,learningPathId:path._id,phaseId:phase._id,moduleId:module._id,title:lesson.title,description:lesson.description,resourceUrl:lesson.resourceUrl||undefined,durationMinutes:lesson.durationMinutes,position:l,scheduledAt,status:scheduledAt?'SCHEDULED':'BACKLOG'});}}}return path._id;}
export async function generatePlan(req:AuthenticatedRequest,res:Response,next:NextFunction){try{const input=requestSchema.parse(req.body);if(!env.OPENAI_API_KEY)return res.status(503).json({message:'AI plan generation is not configured. Set OPENAI_API_KEY on Render.'});const user=await UserModel.findById(req.user!.id).select('timezone').lean();if(!user)return res.status(404).json({message:'User not found'});const prompt=`Create a practical learning plan for ${input.topic}. Duration: ${input.weeks} weeks. Study days: ${input.days.join(', ')}. Start date: ${input.startDate}. Study time: ${input.time} in timezone ${user.timezone}. Session duration: ${input.durationMinutes} minutes. Return ONLY valid JSON with shape {"learningPath":{"title":"...","description":"..."},"phases":[{"title":"...","modules":[{"title":"...","lessons":[{"title":"...","description":"...","date":"YYYY-MM-DD","time":"HH:mm","durationMinutes":60,"resourceUrl":""}]}]}]}. Keep lessons realistic and ordered. Do not include markdown fences.`;const response=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:`Bearer ${env.OPENAI_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({model:env.OPENAI_MODEL,input:prompt})});if(!response.ok){const detail=await response.text();throw new Error(`OpenAI request failed (${response.status}): ${detail.slice(0,300)}`);}const parsed=planSchema.parse(JSON.parse(extractText(await response.json())));const learningPathId=input.save?await persistPlan(req.user!.id,user.timezone,parsed):undefined;res.json({plan:parsed,learningPathId,timezone:user.timezone});}catch(error){next(error);}}
