import type { Response, NextFunction } from 'express';
import { z } from 'zod';
import type { AuthenticatedRequest } from '../middleware/auth.middleware.js';
import { LearningPathModel } from '../models/learning-path.model.js';
import { PhaseModel } from '../models/phase.model.js';
import { ModuleModel } from '../models/module.model.js';
import { LessonModel } from '../models/lesson.model.js';
import { UserModel } from '../models/user.model.js';
import { localDateTimeToUtc } from '../utils/timezone.js';
import { generateAiText, getAiProviderInfo } from '../services/ai-provider.service.js';

const requestSchema=z.object({topic:z.string().min(2).max(120),weeks:z.number().int().min(1).max(52),days:z.array(z.string()).min(1).max(7),time:z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/),durationMinutes:z.number().int().min(15).max(240).default(60),startDate:z.string().regex(/^\d{4}-\d{2}-\d{2}$/),save:z.boolean().default(false)});
const coachSchema=z.object({message:z.string().min(2).max(4000),context:z.string().max(4000).optional()});
const planSchema=z.object({learningPath:z.object({title:z.string().min(2),description:z.string().optional()}),phases:z.array(z.object({title:z.string().min(1),modules:z.array(z.object({title:z.string().min(1),lessons:z.array(z.object({title:z.string().min(1),description:z.string().optional(),date:z.string(),time:z.string(),durationMinutes:z.number().int().min(5).max(480),resourceUrl:z.string().optional()}))}))}))});

async function persistPlan(ownerId:string,timezone:string,rawPlan:unknown){const plan=planSchema.parse(rawPlan);const path=await LearningPathModel.create({ownerId,title:plan.learningPath.title,description:plan.learningPath.description,status:'ACTIVE'});for(let p=0;p<plan.phases.length;p++){const phaseData=plan.phases[p]!;const phase=await PhaseModel.create({ownerId,learningPathId:path._id,title:phaseData.title,position:p});for(let m=0;m<phaseData.modules.length;m++){const moduleData=phaseData.modules[m]!;const module=await ModuleModel.create({ownerId,learningPathId:path._id,phaseId:phase._id,title:moduleData.title,position:m});for(let l=0;l<moduleData.lessons.length;l++){const lesson=moduleData.lessons[l]!;const scheduledAt=localDateTimeToUtc(lesson.date,lesson.time,timezone);await LessonModel.create({ownerId,learningPathId:path._id,phaseId:phase._id,moduleId:module._id,title:lesson.title,description:lesson.description,resourceUrl:lesson.resourceUrl||undefined,durationMinutes:lesson.durationMinutes,position:l,scheduledAt,status:scheduledAt?'SCHEDULED':'BACKLOG'});}}}return path._id;}

export async function generatePlan(req:AuthenticatedRequest,res:Response,next:NextFunction){try{const input=requestSchema.parse(req.body);const provider=getAiProviderInfo();if(!provider.configured)return res.status(503).json({message:`AI plan generation is not configured for ${provider.provider}. Configure an AI provider key on Render.`});const user=await UserModel.findById(req.user!.id).select('timezone').lean();if(!user)return res.status(404).json({message:'User not found'});const prompt=`Create a practical learning plan for ${input.topic}. Duration: ${input.weeks} weeks. Study days: ${input.days.join(', ')}. Start date: ${input.startDate}. Study time: ${input.time} in timezone ${user.timezone}. Session duration: ${input.durationMinutes} minutes. Return ONLY valid JSON with shape {"learningPath":{"title":"...","description":"..."},"phases":[{"title":"...","modules":[{"title":"...","lessons":[{"title":"...","description":"...","date":"YYYY-MM-DD","time":"HH:mm","durationMinutes":60,"resourceUrl":""}]}]}]}. Keep lessons realistic and ordered. Do not include markdown fences.`;const text=await generateAiText(prompt);const parsed=planSchema.parse(JSON.parse(text.replace(/^```json\s*|```$/g,'').trim()));const learningPathId=input.save?await persistPlan(req.user!.id,user.timezone,parsed):undefined;res.json({plan:parsed,learningPathId,timezone:user.timezone,provider:provider.provider});}catch(error){next(error);}}

export async function coach(req:AuthenticatedRequest,res:Response,next:NextFunction){try{const input=coachSchema.parse(req.body);const provider=getAiProviderInfo();if(!provider.configured)return res.status(503).json({message:`AI coach is not configured for ${provider.provider}. Configure an AI provider key on Render.`});const prompt=`You are the LearnFlow learning coach. Help the learner understand concepts, unblock study sessions, break work into realistic next steps, and improve consistency. Do not claim to have changed their LearnFlow data and do not invent completion status. Keep the response concise and practical.\n\nOptional learner context:\n${input.context??'No extra context supplied.'}\n\nLearner message:\n${input.message}`;const answer=await generateAiText(prompt);res.json({answer,provider:provider.provider});}catch(error){next(error);}}

export async function providerStatus(_req:AuthenticatedRequest,res:Response){res.json(getAiProviderInfo());}
