import { randomBytes } from 'node:crypto';
import type { NextFunction, Request, Response } from 'express';
import type { AuthenticatedRequest } from '../middleware/auth.middleware.js';
import { LearningPathModel } from '../models/learning-path.model.js';
import { LessonModel } from '../models/lesson.model.js';

export async function enableProgressShare(req: AuthenticatedRequest,res:Response,next:NextFunction){try{const token=randomBytes(24).toString('hex');const path=await LearningPathModel.findOneAndUpdate({_id:req.params.learningPathId,ownerId:req.user!.id},{$set:{publicShareEnabled:true,publicShareToken:token}},{new:true}).lean();if(!path)return res.status(404).json({message:'Learning path not found'});res.json({token,sharePath:`/share/${token}`});}catch(error){next(error);}}

export async function revokeProgressShare(req:AuthenticatedRequest,res:Response,next:NextFunction){try{const path=await LearningPathModel.findOneAndUpdate({_id:req.params.learningPathId,ownerId:req.user!.id},{$set:{publicShareEnabled:false},$unset:{publicShareToken:1}},{new:true}).lean();if(!path)return res.status(404).json({message:'Learning path not found'});res.status(204).send();}catch(error){next(error);}}

export async function getPublicProgress(req:Request,res:Response,next:NextFunction){try{const path=await LearningPathModel.findOne({publicShareToken:req.params.token,publicShareEnabled:true}).select('title description status createdAt updatedAt').lean();if(!path)return res.status(404).json({message:'Shared learning progress not found'});const lessons=await LessonModel.find({learningPathId:path._id}).select('status durationMinutes scheduledAt completedAt title').sort({scheduledAt:1,createdAt:1}).lean();const totalLessons=lessons.length;const completed=lessons.filter(item=>item.status==='COMPLETED');const completedLessons=completed.length;const completedMinutes=completed.reduce((sum,item)=>sum+(item.durationMinutes||0),0);const completionRate=totalLessons?Math.round((completedLessons/totalLessons)*100):0;const firstScheduled=lessons.find(item=>item.scheduledAt)?.scheduledAt;const lastCompleted=[...completed].reverse().find(item=>item.completedAt)?.completedAt;res.json({title:path.title,description:path.description,status:path.status,completionRate,totalLessons,completedLessons,completedHours:Number((completedMinutes/60).toFixed(1)),startedAt:firstScheduled??path.createdAt,lastActivityAt:lastCompleted??path.updatedAt,isComplete:completionRate===100||path.status==='COMPLETED'});}catch(error){next(error);}}
